### PR TITLE
Miscellanceous

### PR DESCRIPTION
**Pull request by DmitryPustovit**
This works... I think...?
A lot of code and I am just skimming through backlog atm. Will get back to this.

### CODE REVIEW

**Comment by DmitryPustovit** [comment]
Just um... let this sit for a bit

**Comment by DmitryPustovit** [comment]
File renames are fine and were apparently done by me?

**Comment by aowolfie** [comment]
Fixed the issues it was complaining about. They may not be correct, but they are fixed.

**Comment by DmitryPustovit** [comment]
Changes look good.
Only comment is going to be adding python script loading for modules to
execute code/endpoints.
Also need to take a closer look at Main.js and canvas.js.

ETA, tonight

**Comment by DmitryPustovit** [comment]
Haha! More conflicts

**Comment by DmitryPustovit** [comment]
@aowolfie Sanity Check I didn't break something? 

Python code will be refactored to work and loading will be added in 
`DmitryPustovit-pv_1_4-python-module-file-support`

**Review by aowolfie — APPROVED** [review]
Things look okay, some things seems slightly inconsistent though. Some items are hard coded and others are config based.

**Pull request merged**
